'use client';

import { useState, useEffect, useRef } from 'react';
import { useApp } from '@/contexts/AppContext';
import { useAuth } from '@/contexts/AuthContext';
import {
  calculateCorporateTax,
  calculatePersonalTax,
  calculateHSTSummary,
  calculateQSTSummary,
  calculateIntegration,
  getDeductibleAmount,
  calculateHomeOfficeDeduction,
  calculateMileageDeduction,
  calculateSoleProprietorCPP,
} from '@/lib/taxCalculations';
import { formatCurrency, formatPercent, formatDate, today } from '@/lib/formatters';
import { CORPORATE_RATES_2025, PROVINCIAL_CORP_RATES_2025 } from '@/lib/constants';
import styles from './page.module.css';
import { expandRecurringForFY } from '@/lib/recurringUtils';
import Modal from '@/components/ui/Modal';
import Button from '@/components/ui/Button';
import { FormField, Input, Select } from '@/components/ui/FormField';
import { exportS1PDF } from '@/lib/exportHelpers';
import Link from 'next/link';

// ── Review export helpers ────────────────────────────────────────────────────
function buildReviewText(rd, msgs) {
  const sep = '─'.repeat(60);
  const lines = ['AI TAX REVIEW', sep];
  if (rd.summary) lines.push('', rd.summary);
  lines.push('', sep);
  (rd.items || []).forEach((item, i) => {
    const icon = item.category === 'good' ? '✓' : item.category === 'review' ? '⚠' : '→';
    lines.push(`${i + 1}. [${item.category.toUpperCase()}] ${icon} ${item.title}`);
    lines.push(`   ${item.detail}`, '');
  });
  lines.push(sep);
  lines.push('DISCLAIMER: This review is generated by AI and is for general guidance only.');
  lines.push('It is not professional tax advice. Always consult a qualified CPA before filing.');
  if (msgs?.length) {
    lines.push('', sep, 'FOLLOW-UP Q&A', sep, '');
    msgs.forEach(msg => lines.push(`${msg.role === 'user' ? 'YOU' : 'ADVISOR'}: ${msg.content}`, ''));
  }
  return lines.join('\n');
}

function buildReviewMarkdown(rd, msgs) {
  const lines = ['# AI Tax Review', ''];
  if (rd.summary) lines.push(`> ${rd.summary}`, '');
  lines.push('---', '');
  (rd.items || []).forEach(item => {
    const icon = item.category === 'good' ? '✅' : item.category === 'review' ? '⚠️' : '💡';
    lines.push(`### ${icon} ${item.title}`, '', item.detail, '');
  });
  lines.push('---', '');
  lines.push('*This review is generated by AI and is for general guidance only. It is not professional tax advice. Always consult a qualified CPA before filing.*', '');
  if (msgs?.length) {
    lines.push('## Follow-up Q&A', '');
    msgs.forEach(msg => {
      lines.push(msg.role === 'user' ? `**You:** ${msg.content}` : `**Advisor:** ${msg.content}`, '');
    });
  }
  return lines.join('\n');
}

function buildReviewHtml(rd, msgs) {
  const escHtml = s => s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  const catColor = c => c === 'good' ? '#16a34a' : c === 'review' ? '#d97706' : '#4f46e5';
  const catIcon  = c => c === 'good' ? '✅' : c === 'review' ? '⚠️' : '💡';
  let html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>AI Tax Review</title>
<style>
  body{font-family:system-ui,-apple-system,sans-serif;max-width:750px;margin:2rem auto;padding:0 1.5rem;color:#111;line-height:1.6}
  h1{font-size:1.5rem;margin-bottom:0.25rem}
  .summary{background:#f5f5f5;border-left:4px solid #6366f1;padding:0.75rem 1rem;border-radius:4px;margin:1rem 0;font-style:italic}
  .item{display:flex;gap:0.75rem;padding:0.75rem 0;border-bottom:1px solid #e5e5e5}
  .item-icon{font-size:1.1rem;flex-shrink:0;margin-top:2px}
  .item-title{font-weight:700;margin-bottom:0.2rem}
  .item-badge{display:inline-block;font-size:0.68rem;font-weight:700;text-transform:uppercase;padding:1px 6px;border-radius:3px;margin-left:6px;vertical-align:middle}
  .disclaimer{font-size:0.78rem;color:#666;font-style:italic;margin-top:1.5rem;padding-top:0.75rem;border-top:1px solid #e5e5e5}
  .qa-section{margin-top:1.5rem}
  .qa-section h2{font-size:1rem;border-bottom:1px solid #e5e5e5;padding-bottom:0.5rem}
  .qa-msg{margin:0.75rem 0}
  .qa-role{font-size:0.75rem;font-weight:700;text-transform:uppercase;color:#666}
  @media print{body{margin:0}}
</style></head><body>
<h1>AI Tax Review</h1>`;
  if (rd.summary) html += `<div class="summary">${escHtml(rd.summary)}</div>`;
  (rd.items || []).forEach(item => {
    const color = catColor(item.category);
    html += `<div class="item"><div class="item-icon">${catIcon(item.category)}</div>
<div><div class="item-title">${escHtml(item.title)}<span class="item-badge" style="background:${color}20;color:${color}">${item.category}</span></div>
<div>${escHtml(item.detail)}</div></div></div>`;
  });
  html += `<p class="disclaimer">This review is generated by AI and is for general guidance only. It is not professional tax advice. Always consult a qualified CPA before filing.</p>`;
  if (msgs?.length) {
    html += `<div class="qa-section"><h2>Follow-up Q&amp;A</h2>`;
    msgs.forEach(msg => {
      html += `<div class="qa-msg"><div class="qa-role">${msg.role === 'user' ? 'You' : 'Advisor'}</div><div>${escHtml(msg.content)}</div></div>`;
    });
    html += `</div>`;
  }
  html += `</body></html>`;
  return html;
}

export default function TaxesPage() {
  const { state, dispatch, activeFY, activePY, activePersonalYear } = useApp();
  const { user } = useAuth();

  const [s1Exporting, setS1Exporting] = useState(false);
  const [showCCAModal, setShowCCAModal] = useState(false);
  const [ccaEditId,    setCCAEditId]    = useState(null);
  const [ccaForm,      setCCAForm]      = useState({ classNumber: '', description: '', rate: '', openingUCC: '0', additions: '0', disposals: '0', claimedAmount: '0' });
  const [showSLModal,  setShowSLModal]  = useState(false);
  const [slEditId,     setSLEditId]     = useState(null);
  const [slForm,       setSLForm]       = useState({ date: '', description: '', amount: '', type: 'withdrawal' });

  // ── Previous year upload ──────────────────────────
  const [prevYearData, setPrevYearData] = useState(null);
  const [prevYearError, setPrevYearError] = useState('');

  // ── AI Tax Review ────────────────────────────────────────────────
  const [reviewOpen,        setReviewOpen]        = useState(false);
  const [reviewLoading,     setReviewLoading]     = useState(false);
  const [reviewData,        setReviewData]        = useState(null);
  const [reviewError,       setReviewError]       = useState('');
  const [reviewPromptOpen,  setReviewPromptOpen]  = useState(false);
  const [reviewNotes,       setReviewNotes]       = useState('');
  const [reviewTaxData,     setReviewTaxData]     = useState(null);
  const [chatMessages,      setChatMessages]      = useState([]);
  const [chatInput,         setChatInput]         = useState('');
  const [chatLoading,       setChatLoading]       = useState(false);
  const [chatRemaining,     setChatRemaining]     = useState(10);
  const chatScrollRef = useRef(null);

  // Auto-scroll chat to bottom when messages change
  useEffect(() => {
    if (chatScrollRef.current) {
      chatScrollRef.current.scrollTop = chatScrollRef.current.scrollHeight;
    }
  }, [chatMessages, chatLoading]);

  const handlePrevYearFile = e => {
    const file = e.target.files?.[0];
    if (!file) return;
    setPrevYearError('');
    const reader = new FileReader();
    reader.onload = ev => {
      try {
        const json = JSON.parse(ev.target.result);
        // Accept either a full backup or a FY object
        const fyData = json.fiscalYears ? Object.values(json.fiscalYears)[0] : json;
        if (!fyData) throw new Error('Unrecognised format');
        setPrevYearData({
          openingRE: fyData.openingRetainedEarnings ?? fyData.retainedEarnings ?? null,
          shareholderLoan: fyData.shareholderLoan?.openingBalance ?? null,
          ccaClasses: fyData.ccaClasses ?? [],
          label: json.companyName || file.name,
        });
      } catch {
        setPrevYearError('Could not parse file. Please upload a CanBooks backup JSON.');
      }
    };
    reader.readAsText(file);
  };
  const applyPrevYear = () => {
    if (!prevYearData) return;
    if (prevYearData.openingRE !== null) {
      dispatch({ type: 'UPDATE_FISCAL_YEAR', payload: { id: state.activeFiscalYear, openingRetainedEarnings: prevYearData.openingRE } });
    }
    if (prevYearData.shareholderLoan !== null) {
      const existing = activeFY.shareholderLoan ?? { transactions: [] };
      dispatch({ type: 'UPDATE_FISCAL_YEAR', payload: { id: state.activeFiscalYear, shareholderLoan: { ...existing, openingBalance: prevYearData.shareholderLoan } } });
    }
    if (prevYearData.ccaClasses?.length) {
      dispatch({ type: 'UPDATE_FISCAL_YEAR', payload: { id: state.activeFiscalYear, ccaClasses: prevYearData.ccaClasses.map(c => ({ ...c, additions: '0', disposals: '0', claimedAmount: '0' })) } });
    }
    setPrevYearData(null);
  };

  async function runTaxReview(notes = '') {
    setReviewPromptOpen(false);
    setReviewOpen(true);
    setReviewLoading(true);
    setReviewError('');
    setReviewData(null);
    setChatMessages([]);
    setChatRemaining(10);
    setChatInput('');
    try {
      const token = await user.getIdToken();
      // Build expense breakdown by category
      const expByCategory = {};
      for (const exp of expenses) {
        const cat = exp.category || 'other';
        if (!expByCategory[cat]) expByCategory[cat] = { count: 0, total: 0, deductible: 0 };
        expByCategory[cat].count++;
        expByCategory[cat].total = +((expByCategory[cat].total) + (exp.amount || 0)).toFixed(2);
        expByCategory[cat].deductible = +((expByCategory[cat].deductible) + getDeductibleAmount(exp.amount || 0, exp.category, exp.businessUsePercent ?? 100)).toFixed(2);
      }
      const taxData = {
        fiscalYear: state.activeFiscalYear,
        fiscalPeriod: `${activeFY.startDate} to ${activeFY.endDate}`,
        corporate: {
          grossRevenue:     corp.grossRevenue,
          totalDeductions:  totalDeductionsWithHO,
          netIncome:        corp.netIncome,
          sbdIncome:        corp.sbdIncome,
          totalTax:         corp.totalTax,
          effectiveRatePct: +(corp.effectiveRate * 100).toFixed(2),
          afterTaxIncome:   corp.afterTaxIncome,
          closingRetainedEarnings: closingRE,
          openingRetainedEarnings: openingRE,
          totalCCA,
          homeOfficeDeduction: hoResult.deductible,
        },
        expenses: {
          total_count: expenses.length,
          total_amount: +expenses.reduce((s, e) => s + (e.amount || 0), 0).toFixed(2),
          by_category: expByCategory,
          mileage_km: +mileageResult.totalKm.toFixed(1),
          mileage_deduction: mileageResult.deductible,
          cca_total: totalCCA,
          cca_classes: ccaClasses.map(c => ({
            class: c.classNumber,
            description: c.description,
            opening_ucc: c.openingUCC || 0,
            additions: c.additions || 0,
            claimed: c.claimedAmount || 0,
          })),
        },
        invoices: {
          total: invoices.length,
          paid: invoices.filter(i => i.status === 'paid').length,
          sent: invoices.filter(i => i.status === 'sent').length,
          overdue: invoices.filter(i => i.status === 'overdue').length,
          draft: invoices.filter(i => i.status === 'draft').length,
          gross_revenue: corp.grossRevenue,
        },
        personal: {
          taxYear:          activePersonalYear,
          nonEligibleDivs:  activePY.nonEligibleDivs  || 0,
          eligibleDivs:     activePY.eligibleDivs     || 0,
          employmentIncome: activePY.employmentIncome || 0,
          otherIncome:      activePY.otherIncome      || 0,
          rrspDeduction:    activePY.rrspDeduction    || 0,
          rrspRoom:         activePY.rrspRoom         || 0,
          taxWithheld:      activePY.taxWithheld      || 0,
          totalIncome:      personal.totalIncome,
          netIncome:        personal.netIncome,
          totalTax:         personal.totalTax,
          effectiveRatePct: +(personal.effectiveRate * 100).toFixed(2),
          balanceOwing:     personal.balanceOwing,
        },
        hst: {
          collected:     hst.hstCollected,
          itc:           hst.itcTotal,
          netRemittance: hst.netRemittance,
        },
        dividends_paid:          totalDivsPaid,
        shareholder_loan: {
          opening_balance: shareholderLoan.openingBalance || 0,
          closing_balance: slClosingBalance,
          transaction_count: slTransactions.length,
        },
      };
      setReviewTaxData(taxData);
      const res = await fetch('/api/tax-review', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
        body: JSON.stringify({ taxData, userNotes: notes.trim() || undefined }),
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      setReviewData(data);
    } catch (err) {
      setReviewError(err.message || 'Failed to generate review');
    } finally {
      setReviewLoading(false);
    }
  }

  async function sendChatMessage(e) {
    e.preventDefault();
    const question = chatInput.trim();
    if (!question || chatLoading || chatRemaining <= 0) return;
    const newMessages = [...chatMessages, { role: 'user', content: question }];
    setChatMessages(newMessages);
    setChatInput('');
    setChatLoading(true);
    setChatRemaining(r => r - 1);
    try {
      const token = await user.getIdToken();
      const res = await fetch('/api/tax-chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
        body: JSON.stringify({ taxData: reviewTaxData, messages: chatMessages, question }),
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      setChatMessages(prev => [...prev, { role: 'assistant', content: data.answer }]);
    } catch (err) {
      setChatMessages(prev => [...prev, { role: 'assistant', content: `Error: ${err.message}` }]);
    } finally {
      setChatLoading(false);
    }
  }

  // ── Review export actions ───────────────────────────────────────────────
  const [copiedReview, setCopiedReview] = useState(false);

  function copyReview() {
    if (!reviewData) return;
    navigator.clipboard.writeText(buildReviewText(reviewData, chatMessages)).then(() => {
      setCopiedReview(true);
      setTimeout(() => setCopiedReview(false), 2000);
    });
  }

  function downloadReviewTxt() {
    if (!reviewData) return;
    const blob = new Blob([buildReviewText(reviewData, chatMessages)], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url; a.download = 'tax-review.txt'; a.click();
    URL.revokeObjectURL(url);
  }

  function downloadReviewMd() {
    if (!reviewData) return;
    const blob = new Blob([buildReviewMarkdown(reviewData, chatMessages)], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url; a.download = 'tax-review.md'; a.click();
    URL.revokeObjectURL(url);
  }

  function downloadReviewPdf() {
    if (!reviewData) return;
    const html = buildReviewHtml(reviewData, chatMessages);
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(html);
    win.document.close();
    win.onload = () => { win.focus(); win.print(); };
  }

  if (state.activeFiscalYear === 'all') {
    return (
      <div style={{ padding: '3rem 2rem', textAlign: 'center', color: 'var(--text-secondary)' }}>
        <p style={{ fontSize: '1.1rem', fontWeight: 600, marginBottom: '0.5rem' }}>Select a fiscal year to view tax estimates</p>
        <p style={{ fontSize: '0.875rem' }}>Corporate T2 and personal T1 estimates are calculated per fiscal year. Choose a year in the sidebar.</p>
      </div>
    );
  }

  if (!activeFY) return <p>No fiscal year data found.</p>;

  const allFYData = Object.values(state.fiscalYears || {});
  const { startDate, endDate } = activeFY;
  const inRange = date => !date || ((!startDate || date >= startDate) && (!endDate || date <= endDate));
  const invoices      = allFYData.flatMap(fy => fy.invoices || []).filter(inv => inRange(inv.issueDate));
  const baseExpenses   = allFYData.flatMap(fy => fy.expenses || []).filter(exp => inRange(exp.date))
    // Exclude expenses that were manually pushed from the mileage page — mileage is now auto-calculated below
    .filter(exp => !(exp.notes && exp.notes.startsWith('Mileage log auto-calculated')));
  const recurringForFY = startDate && endDate
    ? expandRecurringForFY(state.recurringExpenses || [], startDate, endDate)
    : [];
  const expenses       = [...baseExpenses, ...recurringForFY];
  const homeOffice     = activeFY.homeOffice ?? {};
  const mileageLogs    = activeFY.mileageLogs ?? [];
  const mileageResult  = calculateMileageDeduction(mileageLogs);
  const dividendsPaid  = activeFY.dividendsPaid ?? [];
  const ccaClasses     = activeFY.ccaClasses ?? [];
  const shareholderLoan = activeFY.shareholderLoan ?? { openingBalance: 0, transactions: [] };
  const slTransactions  = shareholderLoan.transactions || [];
  const slClosingBalance = (shareholderLoan.openingBalance || 0) +
    slTransactions.reduce((sum, t) => t.type === 'withdrawal' ? sum + (t.amount || 0) : sum - (t.amount || 0), 0);
  const openingRE  = activeFY.openingRetainedEarnings ?? 0;
  const totalCCA   = ccaClasses.reduce((s, c) => s + (c.claimedAmount || 0), 0);

  const province    = state.settings?.province || 'ON';
  const businessType = state.businessType || 'ccpc';
  const isSoleProp  = businessType === 'sole_prop';
  const isQuebec    = province === 'QC';

  // Revenue
  const grossRevenue = invoices
    .filter(inv => ['sent', 'paid'].includes(inv.status))
    .reduce((s, inv) => s + (inv.subtotal || 0), 0);

  // Expenses — sum up all deductible amounts
  const totalDeductibleExp = expenses.reduce((s, exp) => {
    return s + getDeductibleAmount(exp.amount || 0, exp.category, exp.businessUsePercent ?? 100);
  }, 0);

  // Home office
  const hoResult = calculateHomeOfficeDeduction(homeOffice);
  const totalDeductionsWithHO = totalDeductibleExp + hoResult.deductible + totalCCA + mileageResult.deductible;

  // Corporate tax (province-aware)
  const corp = calculateCorporateTax(grossRevenue, totalDeductionsWithHO, province);

  // HST
  const hst = calculateHSTSummary(invoices, expenses);

  // QST — Quebec only
  const qst = isQuebec ? calculateQSTSummary(invoices, expenses) : null;

  // Sole proprietor CPP (only for sole_prop business type)
  const soleProprietorCPP = isSoleProp
    ? calculateSoleProprietorCPP(Math.max(0, corp.netIncome))
    : null;

  // Dividends paid total
  const totalDivsPaid = dividendsPaid.reduce((s, d) => s + (d.amount || 0), 0);
  const closingRE = openingRE + corp.afterTaxIncome - totalDivsPaid;
  const sortedFYKeys = Object.keys(state.fiscalYears || {}).filter(k => k !== 'all').sort();
  const currentFYIdx = sortedFYKeys.indexOf(state.activeFiscalYear);
  const nextFYKey = currentFYIdx >= 0 && currentFYIdx < sortedFYKeys.length - 1
    ? sortedFYKeys[currentFYIdx + 1] : null;

  // Personal tax
  const personal = calculatePersonalTax({
    nonEligibleDivs:  activePY.nonEligibleDivs  || 0,
    eligibleDivs:     activePY.eligibleDivs     || 0,
    employmentIncome: activePY.employmentIncome || 0,
    otherIncome:      activePY.otherIncome      || 0,
    rrspDeduction:    activePY.rrspDeduction    || 0,
    taxWithheld:      activePY.taxWithheld      || 0,
    cppContributions: activePY.cppContributions || 0,
    eiPremiums:       activePY.eiPremiums       || 0,
    spouseNetIncome:  activePY.spouseNetIncome  ?? null,
  });

  // Integration analysis
  const integrationIncome = corp.netIncome;
  const integration = calculateIntegration(integrationIncome, totalDivsPaid, activePY.rrspDeduction || 0);

  // Filing deadlines
  const fiscalEndYear = activeFY.endDate ? new Date(activeFY.endDate).getFullYear() : new Date().getFullYear();
  const t2Deadline = `${fiscalEndYear + 1}-05-31`;
  const t1Deadline = `${activePersonalYear + 1}-04-30`;
  const hstDeadline = 'Quarterly (Mar/Jun/Sep/Dec) or as per your filing frequency';

  // ── Filing Checklist ───────────────────────────────────────────────────────
  const allInvoicesHaveStatus = invoices.every(inv => inv.status && inv.status !== 'draft');
  const hasOpeningRE = state.activeFiscalYear !== Object.keys(state.fiscalYears || {}).sort()[0];
  const checklist = [
    { id: 'bn', label: 'Business Number (BN9) filled in Settings', done: !!(state.settings?.businessNumber), link: '/settings' },
    { id: 'address', label: 'Company address filled in Settings', done: !!(state.settings?.address && state.settings?.city && state.settings?.postalCode), link: '/settings' },
    { id: 'invoices', label: 'All invoices reviewed — no drafts outstanding', done: allInvoicesHaveStatus },
    { id: 'openingRE', label: 'Opening retained earnings set for this fiscal year', done: openingRE !== 0 || hasOpeningRE },
    { id: 'expenses', label: 'All expenses categorized', done: expenses.every(e => e.category) },
    { id: 'hst', label: 'HST collected and ITC amounts reviewed', done: hst.hstCollected > 0 || invoices.length === 0 },
    { id: 'cca', label: 'CCA classes reviewed and claimed amounts set', done: ccaClasses.every(c => c.claimedAmount >= 0) },
    { id: 'divs', label: 'Dividends paid recorded (or $0 if none)', done: true },
    { id: 'sl', label: 'Shareholder loan balance reconciled', done: slClosingBalance <= 0 || slTransactions.length > 0 },
  ];
  const checklistDone = checklist.filter(c => c.done).length;

  return (
    <div className={styles.page}>
      {/* Header summary */}
      <div className={styles.summaryRow}>
        <SummaryCard label="Corporate Tax Owing" value={formatCurrency(corp.totalTax)} color="danger" sub={`Effective rate: ${formatPercent(corp.effectiveRate)}`} />
        <SummaryCard label={isQuebec ? 'GST Net Remittance' : 'HST Net Remittance'} value={formatCurrency(hst.netRemittance)} color={hst.netRemittance >= 0 ? 'warning' : 'success'} sub={hst.netRemittance < 0 ? 'You have a refund' : 'Amount to remit'} />
        {isQuebec && qst && (
          <SummaryCard label="QST Net Remittance" value={formatCurrency(qst.netQSTRemittance)} color={qst.netQSTRemittance >= 0 ? 'warning' : 'success'} sub={qst.netQSTRemittance < 0 ? 'Revenu Québec owes you' : 'Remit to Revenu Québec'} />
        )}
        <SummaryCard label="Personal Tax Owing" value={formatCurrency(personal.totalTax)} color="danger" sub={`Effective rate: ${formatPercent(personal.effectiveRate)}`} />
        {isSoleProp && soleProprietorCPP && (
          <SummaryCard label="CPP Contributions Owing" value={formatCurrency(soleProprietorCPP.totalCPP)} color="warning" sub="Self-employed CPP (both shares)" />
        )}
        <SummaryCard label="Total Combined Tax" value={formatCurrency(corp.totalTax + personal.totalTax + (soleProprietorCPP?.totalCPP ?? 0))} color="info" sub={isSoleProp ? 'Corporate + Personal + CPP' : 'Corporate + Personal'} />
      </div>

      {/* ── Tax Deadlines shortcut ── */}
      <Link href="/deadlines" style={{ alignSelf: 'flex-end', fontSize: '0.8rem', color: 'var(--accent)', textDecoration: 'none', fontWeight: 600 }}>
        📅 Tax Deadlines →
      </Link>

      {/* ── AI Tax Review ── */}
      <button className={styles.aiReviewBtn} onClick={() => { setReviewNotes(''); setReviewPromptOpen(true); }}>
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <circle cx="12" cy="12" r="10"/>
          <line x1="12" y1="8" x2="12" y2="12"/>
          <line x1="12" y1="16" x2="12.01" y2="16"/>
        </svg>
        AI Tax Review
        <span className={styles.aiReviewBeta}>AI</span>
      </button>

      {/* AI Tax Review — Notes Prompt Modal */}
      <Modal
        isOpen={reviewPromptOpen}
        onClose={() => setReviewPromptOpen(false)}
        title="AI Tax Review"
        size="sm"
        footer={
          <>
            <Button variant="secondary" onClick={() => setReviewPromptOpen(false)}>Cancel</Button>
            <Button onClick={() => runTaxReview(reviewNotes)}>Start Review</Button>
          </>
        }
      >
        <p style={{ marginBottom: '0.75rem', fontSize: '0.875rem', color: 'var(--text-secondary)' }}>
          Optionally add any context or specific questions for the AI to consider when reviewing your tax return.
        </p>
        <textarea
          className={styles.reviewNotesInput}
          placeholder="e.g. I started a side business this year, or should I be splitting salary and dividends differently?"
          value={reviewNotes}
          onChange={e => setReviewNotes(e.target.value)}
          rows={4}
        />
      </Modal>

      {/* AI Tax Review Modal */}
      <Modal isOpen={reviewOpen} onClose={() => setReviewOpen(false)} title="AI Tax Review" size="xl"
        footer={
          <div className={styles.reviewFooterActions}>
            {reviewData && (
              <div className={styles.reviewFooterLeft}>
                <button className={styles.reviewExportBtn} onClick={copyReview}>{copiedReview ? '✓ Copied!' : 'Copy'}</button>
                <button className={styles.reviewExportBtn} onClick={downloadReviewTxt}>↓ TXT</button>
                <button className={styles.reviewExportBtn} onClick={downloadReviewMd}>↓ Markdown</button>
                <button className={styles.reviewExportBtn} onClick={downloadReviewPdf}>↓ PDF</button>
              </div>
            )}
            <Button variant="secondary" onClick={() => setReviewOpen(false)}>Close</Button>
          </div>
        }
      >
        {reviewLoading && (
          <div className={styles.reviewLoading}>
            <div className={styles.reviewSpinner} />
            <p>Analysing your tax data…</p>
          </div>
        )}
        {reviewError && (
          <div className={styles.reviewError}>
            <strong>Error:</strong> {reviewError}
          </div>
        )}
        {reviewData && (
          <div className={styles.reviewBody}>
            {reviewData.summary && (
              <p className={styles.reviewSummary}>{reviewData.summary}</p>
            )}
            <div className={styles.reviewItems}>
              {(reviewData.items || []).map((item, i) => (
                <div key={i} className={`${styles.reviewItem} ${styles[`reviewItem_${item.category}`]}`}>
                  <div className={styles.reviewItemIcon}>
                    {item.category === 'good'   ? '✅' : item.category === 'review' ? '⚠️' : '💡'}
                  </div>
                  <div className={styles.reviewItemBody}>
                    <div className={styles.reviewItemTitle}>{item.title}</div>
                    <div className={styles.reviewItemDetail}>{item.detail}</div>
                  </div>
                </div>
              ))}
            </div>
            <p className={styles.reviewDisclaimer}>
              This review is generated by AI and is for general guidance only. It is not professional tax advice. Always consult a qualified CPA before filing.
            </p>

            {/* ── Chat ── */}
            <div className={styles.chatSection}>
              <div className={styles.chatHeader}>
                <span className={styles.chatTitle}>Ask a follow-up question</span>
                <span className={styles.chatRemaining}>{chatRemaining} question{chatRemaining !== 1 ? 's' : ''} remaining</span>
              </div>
              {chatMessages.length > 0 && (
                <div className={styles.chatMessages} ref={chatScrollRef}>
                  {chatMessages.map((msg, i) => (
                    <div key={i} className={`${styles.chatMsg} ${msg.role === 'user' ? styles.chatMsgUser : styles.chatMsgAssistant}`}>
                      <span className={styles.chatMsgRole}>{msg.role === 'user' ? 'You' : 'Advisor'}</span>
                      <p className={styles.chatMsgContent}>{msg.content}</p>
                    </div>
                  ))}
                  {chatLoading && (
                    <div className={`${styles.chatMsg} ${styles.chatMsgAssistant}`}>
                      <span className={styles.chatMsgRole}>Advisor</span>
                      <p className={styles.chatMsgContent}><span className={styles.chatTyping}>Thinking…</span></p>
                    </div>
                  )}
                </div>
              )}
              {chatRemaining > 0 ? (
                <form className={styles.chatForm} onSubmit={sendChatMessage}>
                  <input
                    className={styles.chatInput}
                    placeholder="e.g. Should I pay myself a salary or dividends? Is my HST correct?"
                    value={chatInput}
                    onChange={e => setChatInput(e.target.value)}
                    disabled={chatLoading}
                  />
                  <Button type="submit" size="sm" disabled={!chatInput.trim() || chatLoading}>Send</Button>
                </form>
              ) : (
                <p className={styles.chatExhausted}>Question limit reached for this session. Re-run the review to start fresh.</p>
              )}
            </div>
          </div>
        )}
      </Modal>

      {/* ── Corporate T2 ── */}
      <Section title="Corporate — T2 Estimate" badge={state.activeFiscalYear}>
        <div className={styles.twoCol}>
          <div>
            <SubSection title="Income & Deductions">
              <Row label="Gross revenue" value={formatCurrency(corp.grossRevenue)} />
              <Row label="Total deductible expenses" value={`− ${formatCurrency(totalDeductibleExp)}`} />
              <Row label="Home office deduction" value={`− ${formatCurrency(hoResult.deductible)}`} />
              {mileageResult.totalKm > 0 && <Row label={`Mileage deduction (${mileageResult.totalKm.toFixed(0)} km)`} value={`− ${formatCurrency(mileageResult.deductible)}`} />}
              {totalCCA > 0 && <Row label="CCA — Schedule 8" value={`− ${formatCurrency(totalCCA)}`} />}
              <Row label="Net income before tax" value={formatCurrency(corp.netIncome)} bold />
            </SubSection>

            <SubSection title="Income Classification">
              <Row label={`SBD income (≤ ${formatCurrency(CORPORATE_RATES_2025.sbd_limit)})`} value={formatCurrency(corp.sbdIncome)} />
              <Row label="General rate income" value={formatCurrency(corp.generalIncome)} />
            </SubSection>
          </div>
          <div>
            <SubSection title="Tax Breakdown">
              <Row label={`Federal SBD tax (${(CORPORATE_RATES_2025.fed_sbd_net * 100).toFixed(1)}%)`} value={formatCurrency(corp.fedTaxSBD)} />
              <Row label={`Federal general tax`} value={formatCurrency(corp.fedTaxGeneral)} />
              <Row label="Federal tax total" value={formatCurrency(corp.fedTax)} bold />
              <div className={styles.dividerRow} />
              <Row label={`${corp.provLabel} SBD tax (${(corp.provSmallRate * 100).toFixed(2)}%)`} value={formatCurrency(corp.provTaxSBD)} />
              <Row label={`${corp.provLabel} general tax (${(corp.provGeneralRate * 100).toFixed(1)}%)`} value={formatCurrency(corp.provTaxGeneral)} />
              <Row label={`${corp.provLabel} tax total`} value={formatCurrency(corp.provTax)} bold />
              <div className={styles.dividerRow} />
              <Row label="Total corporate tax" value={formatCurrency(corp.totalTax)} bold />
              <Row label="After-tax income" value={formatCurrency(corp.afterTaxIncome)} />
              <div className={styles.dividerRow} />
              <RowEditable
                label="Opening retained earnings"
                amount={openingRE}
                onSave={v => dispatch({ type: 'SET_FY_OPENING_RE', payload: { fyKey: state.activeFiscalYear, amount: v } })}
              />
              <Row label="+ After-tax income" value={`+ ${formatCurrency(corp.afterTaxIncome)}`} />
              <Row label="− Dividends paid (this FY)" value={`− ${formatCurrency(totalDivsPaid)}`} />
              <Row label="Closing retained earnings" value={formatCurrency(closingRE)} bold />
              {nextFYKey && (
                <div className={styles.carryRow}>
                  <button
                    className={styles.carryBtn}
                    onClick={() => dispatch({ type: 'SET_FY_OPENING_RE', payload: { fyKey: nextFYKey, amount: closingRE } })}
                  >
                    Copy {formatCurrency(closingRE)} → {nextFYKey} opening RE
                  </button>
                </div>
              )}
            </SubSection>
          </div>
        </div>
        <SubSection title="Shareholder Loans — s.15(2)">
          <div className={styles.slBody}>
            <div className={styles.slBalRow}>
              <span>Opening balance (shareholder owes corp)</span>
              <strong>{formatCurrency(shareholderLoan.openingBalance || 0)}</strong>
            </div>
            {slTransactions.length > 0 ? (
              <table className={styles.slTable}>
                <thead><tr><th>Date</th><th>Description</th><th>Type</th><th>Amount</th><th></th></tr></thead>
                <tbody>
                  {slTransactions.map(t => (
                    <tr key={t.id}>
                      <td>{t.date || '—'}</td>
                      <td>{t.description || '—'}</td>
                      <td><span className={`${styles.slPill} ${t.type === 'withdrawal' ? styles.slPillW : styles.slPillR}`}>{t.type === 'withdrawal' ? 'Withdrawal' : 'Repayment'}</span></td>
                      <td className={styles.slAmt}>{t.type === 'withdrawal' ? '+' : '−'} {formatCurrency(t.amount || 0)}</td>
                      <td>
                        <button className={styles.slDel} onClick={() => dispatch({ type: 'DELETE_SHAREHOLDER_TX', payload: t.id })}>✕</button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            ) : (
              <p className={styles.slEmpty}>No transactions recorded this fiscal year.</p>
            )}
            <div className={styles.slFooter}>
              <button
                className={styles.slAddBtn}
                onClick={() => { setSLEditId(null); setSLForm({ date: today(), description: '', amount: '', type: 'withdrawal' }); setShowSLModal(true); }}
              >
                + Add Transaction
              </button>
              <span>Closing balance: <strong>{formatCurrency(slClosingBalance)}</strong></span>
            </div>
            {slClosingBalance > 0 && (
              <div className={styles.slWarning}>
                ⚠️ Shareholder debit balance of {formatCurrency(slClosingBalance)}. Under s.15(2), this must be repaid within 1 year of the corporate fiscal year end or it becomes employment income.
              </div>
            )}
          </div>
        </SubSection>
        <div className={styles.deadlineBar}>
          <span>📅 T2 filing deadline:</span>
          <strong>{formatDate(t2Deadline)}</strong>
          <span>(6 months after fiscal year end)</span>
          <button
            className={styles.s1Btn}
            disabled={s1Exporting}
            onClick={async () => {
              setS1Exporting(true);
              try { await exportS1PDF(state, state.activeFiscalYear); }
              finally { setS1Exporting(false); }
            }}
          >
            {s1Exporting ? 'Generating…' : '↓ Schedule 1 PDF'}
          </button>
        </div>
      </Section>

      {/* ── CCA Schedule 8 ── */}
      <Section title="Capital Cost Allowance — Schedule 8" badge={state.activeFiscalYear}>
        {ccaClasses.length === 0 ? (
          <p className={styles.ccaEmpty}>No CCA asset classes added yet.</p>
        ) : (
          <div className={styles.ccaScroll}>
            <table className={styles.ccaTable}>
              <thead>
                <tr><th>Class</th><th>Description</th><th>Rate</th><th>Opening UCC</th><th>Additions</th><th>Disposals</th><th>CCA Claimed</th><th>Closing UCC</th><th></th></tr>
              </thead>
              <tbody>
                {ccaClasses.map(c => {
                  const maxC = getMaxCCA(c);
                  const closUCC = getClosingUCC(c);
                  return (
                    <tr key={c.id}>
                      <td><strong>Class {c.classNumber}</strong></td>
                      <td>{c.description || '—'}</td>
                      <td>{((c.rate || 0) * 100).toFixed(0)}%</td>
                      <td>{formatCurrency(c.openingUCC || 0)}</td>
                      <td>{formatCurrency(c.additions || 0)}</td>
                      <td>{formatCurrency(c.disposals || 0)}</td>
                      <td>
                        {formatCurrency(c.claimedAmount || 0)}
                        <span className={styles.ccaMaxNote}> / {formatCurrency(maxC)}</span>
                      </td>
                      <td>{formatCurrency(closUCC)}</td>
                      <td className={styles.ccaRowActions}>
                        <button className={styles.ccaEditBtn} onClick={() => {
                          setCCAEditId(c.id);
                          setCCAForm({ classNumber: c.classNumber, description: c.description || '', rate: ((c.rate || 0) * 100).toString(), openingUCC: (c.openingUCC || 0).toString(), additions: (c.additions || 0).toString(), disposals: (c.disposals || 0).toString(), claimedAmount: (c.claimedAmount || 0).toString() });
                          setShowCCAModal(true);
                        }}>Edit</button>
                        <button className={styles.ccaDelBtn} onClick={() => dispatch({ type: 'DELETE_CCA_CLASS', payload: c.id })}>✕</button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
        <div className={styles.ccaFooter}>
          <button className={styles.ccaAddBtn} onClick={() => { setCCAEditId(null); setCCAForm({ classNumber: '', description: '', rate: '', openingUCC: '0', additions: '0', disposals: '0', claimedAmount: '0' }); setShowCCAModal(true); }}>
            + Add Asset Class
          </button>
          {ccaClasses.length > 0 && (
            <div className={styles.ccaTotalRow}>
              Total CCA claimed: <strong>{formatCurrency(totalCCA)}</strong>
              <span className={styles.ccaTotalNote}> — deducted in T2 net income above</span>
            </div>
          )}
        </div>
      </Section>

      {/* ── Corporate Balance Sheet (S100) ── */}
      <BalanceSheetSection
        activeFY={activeFY}
        invoices={invoices}
        ccaClasses={ccaClasses}
        hst={hst}
        corp={corp}
        slClosingBalance={slClosingBalance}
        closingRE={closingRE}
        dispatch={dispatch}
      />

      {/* ── Personal T1 ── */}
      <Section title="Personal — T1 Estimate" badge={`${activePersonalYear} Tax Year`}>
        <div className={styles.twoCol}>
          <div>
            <SubSection title="Income">
              <Row label="Non-eligible dividends (actual cash)" value={formatCurrency(personal.nonEligibleDivs)} />
              <Row label="Non-eligible dividend gross-up (15%)" value={`+ ${formatCurrency(personal.neGrossedUp - personal.nonEligibleDivs)}`} />
              <Row label="Non-eligible grossed-up" value={formatCurrency(personal.neGrossedUp)} />
              <Row label="Eligible dividends (actual cash)" value={formatCurrency(personal.eligibleDivs)} />
              <Row label="Eligible dividend gross-up (38%)" value={`+ ${formatCurrency(personal.elGrossedUp - personal.eligibleDivs)}`} />
              <Row label="Other income" value={formatCurrency(personal.otherIncome)} />
              <Row label="RRSP deduction" value={`− ${formatCurrency(personal.rrspDeduction)}`} />
              <Row label="Net income (line 23600)" value={formatCurrency(personal.netIncome)} bold />
            </SubSection>
          </div>
          <div>
            <SubSection title="Federal Tax">
              <Row label="Gross federal income tax" value={formatCurrency(personal.fedGrossIncomeTax)} />
              <Row label="Basic personal amount credit" value={`− ${formatCurrency(personal.fedBPA_credit)}`} />
              <Row label="Non-eligible DTC" value={`− ${formatCurrency(personal.fedNeDTC)}`} />
              <Row label="Eligible DTC" value={`− ${formatCurrency(personal.fedElDTC)}`} />
              <Row label="Federal tax" value={formatCurrency(personal.fedTax)} bold />
            </SubSection>
            <SubSection title="Ontario Tax">
              <Row label="Gross Ontario income tax" value={formatCurrency(personal.onGrossIncomeTax)} />
              <Row label="Ontario BPA credit" value={`− ${formatCurrency(personal.onBPA_credit)}`} />
              <Row label="Non-eligible DTC (Ontario)" value={`− ${formatCurrency(personal.onNeDTC)}`} />
              <Row label="Eligible DTC (Ontario)" value={`− ${formatCurrency(personal.onElDTC)}`} />
              <Row label="Ontario basic tax" value={formatCurrency(personal.onBasicTax)} />
              <Row label="Ontario surtax" value={formatCurrency(personal.onSurtax)} />
              <Row label="Ontario Health Premium" value={formatCurrency(personal.ohp)} />
              <Row label="Ontario tax total" value={formatCurrency(personal.onTax)} bold />
            </SubSection>
            <div className={styles.totalBar}>
              <span>Total personal tax</span>
              <strong>{formatCurrency(personal.totalTax)}</strong>
            </div>
          </div>
        </div>
        <div className={styles.deadlineBar}>
          <span>📅 T1 filing deadline:</span>
          <strong>{formatDate(t1Deadline)}</strong>
          <span>(April 30 for most Canadians)</span>
        </div>
      </Section>

      {/* ── Sole Proprietor CPP ── */}
      {isSoleProp && soleProprietorCPP && (
        <Section title="Self-Employment CPP Contributions" badge="Schedule 8 / Line 22200">
          <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', marginBottom: '1rem' }}>
            As a sole proprietor, you pay <strong>both</strong> the employee and employer CPP shares on your net self-employment income.
            The employer half is deductible on line 22200, reducing your taxable income.
          </p>
          <div className={styles.twoCol}>
            <SubSection title="CPP Calculation">
              <Row label="Net self-employment income" value={formatCurrency(soleProprietorCPP.netSelfEmployedIncome)} />
              <Row label="Basic exemption" value={`− ${formatCurrency(soleProprietorCPP.exemption)}`} />
              <Row label="Year's Maximum Pensionable Earnings cap" value={formatCurrency(soleProprietorCPP.maxEarnings)} />
              <Row label="Earnable CPP income" value={formatCurrency(soleProprietorCPP.earnableIncome)} bold />
            </SubSection>
            <SubSection title="Contributions Owing">
              <Row label={`Employee share (${(soleProprietorCPP.cppRate * 100).toFixed(2)}%)`} value={formatCurrency(soleProprietorCPP.employeeShare)} />
              <Row label={`Employer share (${(soleProprietorCPP.cppRate * 100).toFixed(2)}%)`} value={formatCurrency(soleProprietorCPP.employerShare)} />
              <Row label="Total CPP owing" value={formatCurrency(soleProprietorCPP.totalCPP)} bold />
              <div className={styles.dividerRow} />
              <Row label="Employer half deductible (line 22200)" value={`− ${formatCurrency(soleProprietorCPP.deductibleAmount)}`} />
              <Row label="Net CPP cost after deduction" value={formatCurrency(soleProprietorCPP.totalCPP - soleProprietorCPP.deductibleAmount)} />
            </SubSection>
          </div>
          <div className={styles.alertBox} style={{ marginTop: '0.75rem', borderColor: 'var(--warning)', background: 'var(--warning-bg, #fffbeb)' }}>
            💡 Add {formatCurrency(soleProprietorCPP.totalCPP)} CPP to your tax set-aside.
            The employer half ({formatCurrency(soleProprietorCPP.deductibleAmount)}) reduces your T1 line 22200.
          </div>
        </Section>
      )}
      <Section title={isQuebec ? 'GST Summary' : 'HST Summary'} badge={isQuebec ? 'Quebec 5% GST' : `${corp.provLabel} HST`}>
        <div className={styles.hstGrid}>
          <div className={styles.hstCard}>
            <span className={styles.hstLabel}>{isQuebec ? 'GST Collected' : 'HST Collected'}</span>
            <strong className={styles.hstValue}>{formatCurrency(hst.hstCollected)}</strong>
            <span className={styles.hstSub}>From invoices (sent + paid)</span>
          </div>
          <div className={styles.hstCard}>
            <span className={styles.hstLabel}>Input Tax Credits (ITCs)</span>
            <strong className={styles.hstValue} style={{ color: 'var(--success)' }}>{formatCurrency(hst.itcTotal)}</strong>
            <span className={styles.hstSub}>{isQuebec ? 'GST' : 'HST'} paid on business expenses</span>
          </div>
          <div className={`${styles.hstCard} ${styles.hstCardTotal}`}>
            <span className={styles.hstLabel}>Net Remittance</span>
            <strong className={`${styles.hstValue} ${hst.netRemittance < 0 ? styles.hstCredit : ''}`}>{formatCurrency(Math.abs(hst.netRemittance))}</strong>
            <span className={styles.hstSub}>{hst.netRemittance < 0 ? 'CRA owes you a refund' : 'Amount to remit to CRA'}</span>
          </div>
        </div>
        <div className={styles.deadlineBar}>
          <span>📅 {isQuebec ? 'GST' : 'HST'} remittance:</span>
          <strong>Quarterly</strong>
          <span>— check your CRA account for exact due dates</span>
        </div>
        {!state.settings?.hstRegistered && (
          <div className={styles.alertBox}>⚠️ You are marked as not HST registered. Update in Settings if your revenue exceeds $30,000.</div>
        )}
      </Section>

      {/* ── QST (Quebec only) ── */}
      {isQuebec && qst && (
        <Section title="QST Summary" badge="Quebec 9.975%">
          <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', marginBottom: '1rem' }}>
            Quebec businesses file GST with the CRA <em>and</em> QST separately with Revenu Québec. Both are tracked independently.
          </p>
          <div className={styles.hstGrid}>
            <div className={styles.hstCard}>
              <span className={styles.hstLabel}>QST Collected</span>
              <strong className={styles.hstValue}>{formatCurrency(qst.qstCollected)}</strong>
              <span className={styles.hstSub}>From invoices (QST amount field)</span>
            </div>
            <div className={styles.hstCard}>
              <span className={styles.hstLabel}>QST Input Tax Refunds</span>
              <strong className={styles.hstValue} style={{ color: 'var(--success)' }}>{formatCurrency(qst.qstITC)}</strong>
              <span className={styles.hstSub}>QST paid on business expenses</span>
            </div>
            <div className={`${styles.hstCard} ${styles.hstCardTotal}`}>
              <span className={styles.hstLabel}>Net QST Remittance</span>
              <strong className={`${styles.hstValue} ${qst.netQSTRemittance < 0 ? styles.hstCredit : ''}`}>{formatCurrency(Math.abs(qst.netQSTRemittance))}</strong>
              <span className={styles.hstSub}>{qst.netQSTRemittance < 0 ? 'Revenu Québec owes you' : 'Remit to Revenu Québec'}</span>
            </div>
          </div>
          <div className={styles.deadlineBar}>
            <span>📅 QST remittance:</span>
            <strong>Quarterly</strong>
            <span>— check your Revenu Québec account for exact due dates</span>
          </div>
          {qst.qstCollected === 0 && (
            <div className={styles.alertBox}>
              ℹ️ No QST collected. Add a <strong>qst</strong> amount field to your invoices to track QST. Rate: 9.975% on the pre-GST price.
            </div>
          )}
        </Section>
      )}

      {/* ── Integration Analysis ── */}
      <Section title="Tax Integration Analysis" badge="Corp + Personal">
        <p className={styles.integrationBlurb}>
          Tax integration measures how efficiently income earned through a corporation is taxed when paid out as dividends vs. earning the same income personally.
        </p>
        <div className={styles.integrationGrid}>
          <IntItem label="Corporate tax on net income" value={formatCurrency(integration.corporateTax)} />
          <IntItem label="Personal tax on dividends" value={formatCurrency(integration.personalTax)} />
          <IntItem label="Combined corp + personal tax" value={formatCurrency(integration.combinedTax)} bold />
          <IntItem label="Tax if earned personally (no corp)" value={formatCurrency(integration.personalOnlyTax)} />
          <IntItem label="Tax difference (corp route minus personal)" value={formatCurrency(integration.taxDifference)} color={integration.taxDifference < 0 ? 'success' : integration.taxDifference > 0 ? 'danger' : ''} />
          <IntItem label="After-tax kept (corpo route)" value={`${integration.integrationEfficiency.toFixed(1)}% of corp income`} />
        </div>
        {Math.abs(integration.taxDifference) > 100 && (
          <div className={styles.integrationNote}>
            {integration.taxDifference < 0
              ? `✅ The corporate route saves ${formatCurrency(Math.abs(integration.taxDifference))} in total tax compared to earning this income personally. The deferral benefit from leaving money in the corp is not included here.`
              : `⚠️ The corporate route costs ${formatCurrency(integration.taxDifference)} more in combined tax. This may be due to timing of dividend payments or income level. Consider consulting a tax professional.`}
          </div>
        )}
      </Section>

      {/* ── T2 Filing Checklist ── */}
      <Section title="T2 Filing Checklist" badge={`${checklistDone}/${checklist.length} complete`}>
        <div className={styles.checklistGrid}>
          {checklist.map(item => (
            <div key={item.id} className={`${styles.checklistItem} ${item.done ? styles.checklistDone : styles.checklistPending}`}>
              <span className={styles.checklistIcon}>{item.done ? '✅' : '⬜'}</span>
              <span className={styles.checklistLabel}>
                {item.label}
                {item.link && !item.done && (
                  <a href={item.link} className={styles.checklistLink}> → Fix in Settings</a>
                )}
              </span>
            </div>
          ))}
        </div>
        {checklistDone === checklist.length && (
          <div className={styles.checklistComplete}>
            ✅ All checklist items complete — you're ready to file!
          </div>
        )}
      </Section>

      {/* ── Previous Year Upload ── */}
      <Section title="Import Previous Year Data">
        <div className={styles.prevYearBox}>
          <p className={styles.prevYearNote}>Upload a prior-year CanBooks backup JSON to pre-fill opening retained earnings, shareholder loan balance, and CCA class UCCs into the current fiscal year. <strong>Nothing is uploaded to any server — all processing happens in your browser.</strong></p>
          <label className={styles.prevYearLabel}>
            <span>Select backup file (.json)</span>
            <input type="file" accept=".json,application/json" onChange={handlePrevYearFile} className={styles.prevYearFileInput} />
          </label>
          {prevYearError && <p className={styles.prevYearError}>{prevYearError}</p>}
          {prevYearData && (
            <div className={styles.prevYearPreview}>
              <div className={styles.prevYearPreviewTitle}>Found in {prevYearData.label}:</div>
              <ul className={styles.prevYearList}>
                {prevYearData.openingRE !== null && <li>Opening Retained Earnings: <strong>{formatCurrency(prevYearData.openingRE)}</strong></li>}
                {prevYearData.shareholderLoan !== null && <li>Shareholder Loan Opening Balance: <strong>{formatCurrency(prevYearData.shareholderLoan)}</strong></li>}
                {prevYearData.ccaClasses?.length > 0 && <li>{prevYearData.ccaClasses.length} CCA class{prevYearData.ccaClasses.length !== 1 ? 'es' : ''} (additions/disposals will be reset to 0)</li>}
              </ul>
              <div style={{ display: 'flex', gap: '0.5rem', marginTop: '0.75rem' }}>
                <Button onClick={applyPrevYear}>Apply to Current Year</Button>
                <Button variant="secondary" onClick={() => setPrevYearData(null)}>Discard</Button>
              </div>
            </div>
          )}
        </div>
      </Section>

      {/* ── Disclaimer ── */}
      <div className={styles.globalDisclaimer}>
        <strong>⚠️ Estimates only.</strong> This tool uses 2025 Canadian federal and Ontario provincial tax rates and simplifies many CRA rules. It does not account for instalment payments, prior-year balances, all credits, or complex situations. Always verify with a CPA or licensed tax professional before filing.
      </div>

      {/* ── Shareholder Loan Modal ── */}
      <Modal isOpen={showSLModal} onClose={() => setShowSLModal(false)} title={slEditId ? 'Edit Transaction' : 'Add SHL Transaction'} size="sm">
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.875rem' }}>
          <FormField label="Date"><Input type="date" value={slForm.date} onChange={e => setSLForm(f => ({ ...f, date: e.target.value }))} /></FormField>
          <FormField label="Description"><Input type="text" placeholder="e.g. Owner withdrawal" value={slForm.description} onChange={e => setSLForm(f => ({ ...f, description: e.target.value }))} /></FormField>
          <FormField label="Amount"><Input type="number" prefix="$" step="0.01" value={slForm.amount} onChange={e => setSLForm(f => ({ ...f, amount: e.target.value }))} /></FormField>
          <FormField label="Type">
            <Select value={slForm.type} onChange={e => setSLForm(f => ({ ...f, type: e.target.value }))}>
              <option value="withdrawal">Withdrawal (SH takes from corp)</option>
              <option value="repayment">Repayment (SH pays corp back)</option>
            </Select>
          </FormField>
        </div>
        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.5rem', marginTop: '1.25rem' }}>
          <Button variant="ghost" onClick={() => setShowSLModal(false)}>Cancel</Button>
          <Button onClick={() => {
            const amt = parseFloat(slForm.amount);
            if (isNaN(amt) || amt <= 0) return;
            dispatch({ type: slEditId ? 'UPDATE_SHAREHOLDER_TX' : 'ADD_SHAREHOLDER_TX', payload: { ...(slEditId ? { id: slEditId } : {}), ...slForm, amount: amt } });
            setShowSLModal(false);
          }}>Save</Button>
        </div>
      </Modal>

      {/* ── CCA Modal ── */}
      <Modal isOpen={showCCAModal} onClose={() => setShowCCAModal(false)} title={ccaEditId ? 'Edit Asset Class' : 'Add CCA Asset Class'} size="md">
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.875rem' }}>
          <FormField label="CCA Class #" hint="e.g. 8, 10, 50">
            <Input type="text" placeholder="8" value={ccaForm.classNumber} onChange={e => {
              const m = CCA_COMMON_CLASSES.find(c => c.num === e.target.value);
              setCCAForm(f => ({ ...f, classNumber: e.target.value, rate: m ? (m.rate * 100).toString() : f.rate }));
            }} />
          </FormField>
          <FormField label="Rate (%)" hint="e.g. 20 for 20%">
            <Input type="number" step="0.01" value={ccaForm.rate} onChange={e => setCCAForm(f => ({ ...f, rate: e.target.value }))} />
          </FormField>
          <div style={{ gridColumn: 'span 2' }}>
            <FormField label="Description">
              <Input type="text" placeholder="e.g. Office furniture, MacBook Pro" value={ccaForm.description} onChange={e => setCCAForm(f => ({ ...f, description: e.target.value }))} />
            </FormField>
          </div>
          <FormField label="Opening UCC" hint="UCC at start of FY">
            <Input type="number" prefix="$" step="0.01" value={ccaForm.openingUCC} onChange={e => setCCAForm(f => ({ ...f, openingUCC: e.target.value }))} />
          </FormField>
          <FormField label="Additions this FY">
            <Input type="number" prefix="$" step="0.01" value={ccaForm.additions} onChange={e => setCCAForm(f => ({ ...f, additions: e.target.value }))} />
          </FormField>
          <FormField label="Disposals this FY">
            <Input type="number" prefix="$" step="0.01" value={ccaForm.disposals} onChange={e => setCCAForm(f => ({ ...f, disposals: e.target.value }))} />
          </FormField>
          <FormField
            label="CCA Claimed"
            hint={`Max: ${formatCurrency(getMaxCCA({ rate: parseFloat(ccaForm.rate) / 100 || 0, openingUCC: parseFloat(ccaForm.openingUCC) || 0, additions: parseFloat(ccaForm.additions) || 0, disposals: parseFloat(ccaForm.disposals) || 0 }))}`}
          >
            <Input type="number" prefix="$" step="0.01" value={ccaForm.claimedAmount} onChange={e => setCCAForm(f => ({ ...f, claimedAmount: e.target.value }))} />
          </FormField>
        </div>
        <div className={styles.ccaClassChips}>
          {CCA_COMMON_CLASSES.map(c => (
            <button key={c.num} className={styles.ccaChip} type="button"
              onClick={() => setCCAForm(f => ({ ...f, classNumber: c.num, rate: (c.rate * 100).toString() }))}>
              Class {c.num} — {c.label} ({(c.rate * 100).toFixed(0)}%)
            </button>
          ))}
        </div>
        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.5rem', marginTop: '1.25rem' }}>
          <Button variant="ghost" onClick={() => setShowCCAModal(false)}>Cancel</Button>
          <Button onClick={() => {
            const rate = parseFloat(ccaForm.rate) / 100;
            const payload = {
              classNumber: ccaForm.classNumber,
              description: ccaForm.description,
              rate: isNaN(rate) ? 0 : rate,
              openingUCC: parseFloat(ccaForm.openingUCC) || 0,
              additions: parseFloat(ccaForm.additions) || 0,
              disposals: parseFloat(ccaForm.disposals) || 0,
              claimedAmount: parseFloat(ccaForm.claimedAmount) || 0,
            };
            dispatch({ type: ccaEditId ? 'UPDATE_CCA_CLASS' : 'ADD_CCA_CLASS', payload: ccaEditId ? { id: ccaEditId, ...payload } : payload });
            setShowCCAModal(false);
          }}>Save</Button>
        </div>
      </Modal>
    </div>
  );
}

// ─── Balance Sheet Section ───────────────────────────────────────────────────
function BalanceSheetSection({ activeFY, invoices, ccaClasses, hst, corp, slClosingBalance, closingRE, dispatch }) {
  const bs      = activeFY.balanceSheet ?? {};
  const [form, setForm] = useState({
    manualCash:                bs.manualCash              ?? '',
    otherCurrentAssets:        bs.otherCurrentAssets       ?? 0,
    otherLongTermAssets:       bs.otherLongTermAssets      ?? 0,
    accountsPayable:           bs.accountsPayable          ?? 0,
    otherCurrentLiabilities:   bs.otherCurrentLiabilities  ?? 0,
    longTermDebt:              bs.longTermDebt             ?? 0,
    shareCapital:              bs.shareCapital             ?? 1,
  });
  const [saved, setSaved] = useState(false);

  // Re-sync when FY changes
  useEffect(() => {
    const b = activeFY.balanceSheet ?? {};
    setForm({
      manualCash:              b.manualCash              ?? '',
      otherCurrentAssets:      b.otherCurrentAssets      ?? 0,
      otherLongTermAssets:     b.otherLongTermAssets     ?? 0,
      accountsPayable:         b.accountsPayable         ?? 0,
      otherCurrentLiabilities: b.otherCurrentLiabilities ?? 0,
      longTermDebt:            b.longTermDebt            ?? 0,
      shareCapital:            b.shareCapital            ?? 1,
    });
  }, [activeFY]); // eslint-disable-line react-hooks/exhaustive-deps

  // Auto-computed values
  const latestStmt = [...(activeFY.bankStatements || [])].sort((a, b) =>
    (b.periodEnd || '').localeCompare(a.periodEnd || '')).find(s => s.closingBalance != null);
  const autoCash = latestStmt?.closingBalance ?? 0;
  const cash     = form.manualCash !== '' ? parseFloat(form.manualCash) || 0 : autoCash;

  const ar = invoices.filter(inv => inv.status === 'sent').reduce((s, inv) => s + (inv.total || 0), 0);

  const equipmentUCC = ccaClasses.reduce((s, c) => {
    const net = (c.openingUCC || 0) + (c.additions || 0) - (c.disposals || 0) - (c.claimedAmount || 0);
    return s + Math.max(0, net);
  }, 0);

  const hstPayable  = Math.max(0, hst.netRemittance);
  const taxPayable  = Math.max(0, corp.totalTax);
  const slLiability = Math.max(0, -slClosingBalance); // negative = shareholder owes corp (unlikely); positive = corp owes shareholder

  // Balance sheet totals
  const totalCurrentAssets  = cash + ar + (parseFloat(form.otherCurrentAssets) || 0);
  const totalLongTermAssets  = equipmentUCC + (parseFloat(form.otherLongTermAssets) || 0);
  const totalAssets          = totalCurrentAssets + totalLongTermAssets;

  const totalCurrentLiab     = (parseFloat(form.accountsPayable) || 0) + hstPayable + taxPayable + (parseFloat(form.otherCurrentLiabilities) || 0);
  const totalLongTermLiab    = (parseFloat(form.longTermDebt) || 0);
  const shareCapitalAmt      = parseFloat(form.shareCapital) || 1;
  const totalEquity           = shareCapitalAmt + closingRE + slLiability;
  const totalLiabEquity       = totalCurrentLiab + totalLongTermLiab + totalEquity;
  const difference            = Math.abs(totalAssets - totalLiabEquity);

  const save = e => {
    e.preventDefault();
    dispatch({ type: 'UPDATE_BALANCE_SHEET', payload: {
      manualCash:              form.manualCash !== '' ? parseFloat(form.manualCash) || 0 : null,
      otherCurrentAssets:      parseFloat(form.otherCurrentAssets)      || 0,
      otherLongTermAssets:     parseFloat(form.otherLongTermAssets)     || 0,
      accountsPayable:         parseFloat(form.accountsPayable)         || 0,
      otherCurrentLiabilities: parseFloat(form.otherCurrentLiabilities) || 0,
      longTermDebt:            parseFloat(form.longTermDebt)            || 0,
      shareCapital:            parseFloat(form.shareCapital)            || 1,
    } });
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  };
  const f = v => '$' + Math.abs(v).toLocaleString('en-CA', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  return (
    <Section title="Corporate Balance Sheet (S100)" badge="Year-end">
      <p className={styles.bsIntro}>Used for FutureTax Schedule 100. Auto-filled values come from your app data — enter any manual overrides and save.</p>
      <form onSubmit={save}>
        <div className={styles.bsGrid}>
          {/* Assets */}
          <div className={styles.bsCol}>
            <div className={styles.bsColTitle}>Assets</div>
            <div className={styles.bsSection}>Current Assets</div>
            <div className={styles.bsRow}>
              <span className={styles.bsLabel}>Cash / Bank <span className={styles.bsAuto}>(auto)</span></span>
              <span className={styles.bsValue}>{f(autoCash)}</span>
              <input className={styles.bsOverride} type="number" step="0.01" placeholder="Override…" value={form.manualCash} onChange={e => setForm(p => ({ ...p, manualCash: e.target.value }))} />
            </div>
            <div className={styles.bsRow}>
              <span className={styles.bsLabel}>Accounts Receivable <span className={styles.bsAuto}>(auto)</span></span>
              <span className={styles.bsValue}>{f(ar)}</span>
            </div>
            <div className={styles.bsRow}>
              <span className={styles.bsLabel}>Other Current Assets</span>
              <input className={styles.bsInput} type="number" step="0.01" min="0" value={form.otherCurrentAssets} onChange={e => setForm(p => ({ ...p, otherCurrentAssets: e.target.value }))} />
            </div>
            <div className={styles.bsSubtotal}><span>Total Current Assets</span><strong>{f(totalCurrentAssets)}</strong></div>

            <div className={styles.bsSection}>Capital / Long-term</div>
            <div className={styles.bsRow}>
              <span className={styles.bsLabel}>Equipment / CCA UCC <span className={styles.bsAuto}>(auto)</span></span>
              <span className={styles.bsValue}>{f(equipmentUCC)}</span>
            </div>
            <div className={styles.bsRow}>
              <span className={styles.bsLabel}>Other Long-term Assets</span>
              <input className={styles.bsInput} type="number" step="0.01" min="0" value={form.otherLongTermAssets} onChange={e => setForm(p => ({ ...p, otherLongTermAssets: e.target.value }))} />
            </div>
            <div className={styles.bsSubtotal}><span>Total Assets</span><strong>{f(totalAssets)}</strong></div>
          </div>

          {/* Liabilities + Equity */}
          <div className={styles.bsCol}>
            <div className={styles.bsColTitle}>Liabilities &amp; Equity</div>
            <div className={styles.bsSection}>Current Liabilities</div>
            <div className={styles.bsRow}>
              <span className={styles.bsLabel}>Accounts Payable</span>
              <input className={styles.bsInput} type="number" step="0.01" min="0" value={form.accountsPayable} onChange={e => setForm(p => ({ ...p, accountsPayable: e.target.value }))} />
            </div>
            <div className={styles.bsRow}>
              <span className={styles.bsLabel}>HST/GST Payable <span className={styles.bsAuto}>(auto)</span></span>
              <span className={styles.bsValue}>{f(hstPayable)}</span>
            </div>
            <div className={styles.bsRow}>
              <span className={styles.bsLabel}>Income Tax Payable <span className={styles.bsAuto}>(auto)</span></span>
              <span className={styles.bsValue}>{f(taxPayable)}</span>
            </div>
            <div className={styles.bsRow}>
              <span className={styles.bsLabel}>Other Current Liabilities</span>
              <input className={styles.bsInput} type="number" step="0.01" min="0" value={form.otherCurrentLiabilities} onChange={e => setForm(p => ({ ...p, otherCurrentLiabilities: e.target.value }))} />
            </div>
            <div className={styles.bsSubtotal}><span>Total Current Liabilities</span><strong>{f(totalCurrentLiab)}</strong></div>

            <div className={styles.bsSection}>Long-term Liabilities</div>
            <div className={styles.bsRow}>
              <span className={styles.bsLabel}>Long-term Debt / Loans</span>
              <input className={styles.bsInput} type="number" step="0.01" min="0" value={form.longTermDebt} onChange={e => setForm(p => ({ ...p, longTermDebt: e.target.value }))} />
            </div>

            <div className={styles.bsSection}>Equity</div>
            <div className={styles.bsRow}>
              <span className={styles.bsLabel}>Share Capital</span>
              <input className={styles.bsInput} type="number" step="0.01" min="0" value={form.shareCapital} onChange={e => setForm(p => ({ ...p, shareCapital: e.target.value }))} />
            </div>
            <div className={styles.bsRow}>
              <span className={styles.bsLabel}>Retained Earnings <span className={styles.bsAuto}>(auto)</span></span>
              <span className={styles.bsValue}>{f(closingRE)}</span>
            </div>
            <div className={styles.bsSubtotal}><span>Total Liabilities &amp; Equity</span><strong>{f(totalLiabEquity)}</strong></div>
          </div>
        </div>

        {difference > 1 && (
          <div className={styles.bsImbalance}>
            ⚠️ Balance sheet is out of balance by {f(difference)}. Review accounts payable, shareholder loan, or other manual entries.
          </div>
        )}
        {difference <= 1 && totalAssets > 0 && (
          <div className={styles.bsBalanced}>✅ Balance sheet balances — Assets = Liabilities + Equity ({f(totalAssets)})</div>
        )}

        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginTop: '1rem' }}>
          <Button type="submit" size="sm">Save Balance Sheet</Button>
          {saved && <span style={{ fontSize: '0.8rem', color: 'var(--success)' }}>✅ Saved!</span>}
        </div>
      </form>
    </Section>
  );
}

function Section({ title, badge, children }) {
  return (
    <section className={styles.section}>
      <div className={styles.sectionHead}>
        <h2 className={styles.sectionTitle}>{title}</h2>
        {badge && <span className={styles.sectionBadge}>{badge}</span>}
      </div>
      <div className={styles.sectionBody}>{children}</div>
    </section>
  );
}

function SubSection({ title, children }) {
  return (
    <div className={styles.subSection}>
      <div className={styles.subSectionTitle}>{title}</div>
      {children}
    </div>
  );
}

function Row({ label, value, bold }) {
  return (
    <div className={`${styles.row} ${bold ? styles.rowBold : ''}`}>
      <span>{label}</span>
      <span>{value}</span>
    </div>
  );
}

function SummaryCard({ label, value, color, sub }) {
  return (
    <div className={`${styles.summaryCard} ${styles[`summaryCard_${color}`]}`}>
      <span className={styles.summaryLabel}>{label}</span>
      <strong className={styles.summaryValue}>{value}</strong>
      {sub && <span className={styles.summarySub}>{sub}</span>}
    </div>
  );
}

function IntItem({ label, value, bold, color }) {
  return (
    <div className={`${styles.intItem} ${bold ? styles.intItemBold : ''} ${color ? styles[`intItem_${color}`] : ''}`}>
      <span>{label}</span>
      <strong>{value}</strong>
    </div>
  );
}

function RowEditable({ label, amount, onSave }) {
  const [editing, setEditing] = useState(false);
  const [input, setInput]     = useState('');
  const commit = () => { const n = parseFloat(input); if (!isNaN(n)) onSave(n); setEditing(false); };
  if (editing) {
    return (
      <div className={styles.row}>
        <span>{label}</span>
        <input
          className={styles.reInput}
          type="number"
          step="0.01"
          value={input}
          onChange={e => setInput(e.target.value)}
          onBlur={commit}
          onKeyDown={e => { if (e.key === 'Enter') commit(); if (e.key === 'Escape') setEditing(false); }}
          autoFocus
        />
      </div>
    );
  }
  return (
    <div className={styles.row}>
      <span>{label}</span>
      <span className={styles.reEditWrap}>
        {formatCurrency(amount)}
        <button className={styles.reEditBtn} onClick={() => { setInput(amount.toString()); setEditing(true); }} title="Edit">✎</button>
      </span>
    </div>
  );
}

const CCA_COMMON_CLASSES = [
  { num: '1',    rate: 0.04,  label: 'Buildings' },
  { num: '8',    rate: 0.20,  label: 'Office equip / furniture' },
  { num: '10',   rate: 0.30,  label: 'Motor vehicles' },
  { num: '10.1', rate: 0.30,  label: 'Passenger vehicles (>$37k cap)' },
  { num: '12',   rate: 1.00,  label: 'Small tools (<$500)' },
  { num: '14.1', rate: 0.05,  label: 'Goodwill / intangibles' },
  { num: '50',   rate: 0.55,  label: 'Computers / data equip' },
  { num: '53',   rate: 0.50,  label: 'M&P machinery' },
  { num: '54',   rate: 0.30,  label: 'Zero-emission vehicles' },
];

function getMaxCCA(c) {
  const netAdd = (c.additions || 0) - (c.disposals || 0);
  const base = netAdd >= 0
    ? (c.openingUCC || 0) + netAdd * 0.5   // half-year rule on net additions
    : Math.max(0, (c.openingUCC || 0) + netAdd);
  return Math.max(0, base * (c.rate || 0));
}

function getClosingUCC(c) {
  return Math.max(0, (c.openingUCC || 0) + (c.additions || 0) - (c.disposals || 0) - (c.claimedAmount || 0));
}
